# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Isha Khurana
title: Quantitative Analyst
email: ishakhurana1996@gmail.com
website: https://ishakhurana17.github.io
# Social links
# twitter_username: pranjalpatni09
github_username:  ishakhurana17
# dribbble_username: <>
# facebook_username: <>
# flickr_username: <>
# instagram_username: pranjal.patni
linkedin_username: ishakhurana17
# pinterest_username: <>
#youtube_username: <>
# googleplus_username: <>

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi! I am <mark>Isha Khurana</mark>. I am a graduate student, pursuing STEM certified Masters program in Computational Finance from Rochester Institute of Technology, NY.
  
  I hold professional experience in project management, financial modeling and data analysis. Currently, I am seeking a full time opportunity, starting December 2020, for quantitative or analytical role.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  My hobbies include:
   - Reading
   - Photography
   - Dancing
   - Traveling
   - Playing tennis
   - Swimming

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
